version: "3.7"

services:
  nginx:
   container_name: nginx
   build: ./requirements/nginx/.
   env_file: .env
   networks: 
     - inception
   ports:
     - "443:443"
   expose:
     - "443"
   restart: on-failure
   volumes:
     - wordpress-vol:/var/www/html/
   depends_on:
     - wordpress

  mariadb:
   container_name: mariadb
   build: requirements/mariadb/.
   env_file: .env
   networks:
    - inception
   restart: on-failure
   volumes:
    - mariadb-vol:/var/lib/mysql/

  wordpress:
   container_name: wordpress
   build: requirements/wordpress/. 
   env_file: .env
   networks:
     -  inception
   restart: on-failure
   volumes:
    - wordpress-vol:/var/www/html/
   depends_on:
     - mariadb

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA}/wordpress-vol

  mariadb-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA}/mariadb-vol
